pool:
  vmImage: 'ubuntu-latest'
  
resources:
  repositories:
    - repository: efm-eproc-pipeline
      type: github
      name: felleslosninger/efm-eproc-pipeline
      endpoint: felleslosninger
      ref: development

extends:
  template: build-and-deploy-template.yml@efm-eproc-pipeline
  parameters:
    environmentRepository: git://eformidling/eformidling
    buildDockerArtifact: true
    jiraVersionPrefix: SR

trigger:
  batch: true
  branches:
    include:
      - '*'

pr: none
