server:
  port: 8080
  servlet:
    context-path: /adressetjeneste
management:
  server:
    port: 8090
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: "info,env,prometheus,health"
    enabled-by-default: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
  security:
    user:
      name: ${ADMIN_API_USERNAME}
      password: ${ADMIN_API_PASSWORD}

difi:
  move:
    fiks:
      io:
        enable: true
        integrasjon-id: ${FIKSIO_ID}
        integrasjon-passord: ${FIKSIO_PASSWORD}
      svarut:
        user: ${SVARUT_USER}
        password: ${SVARUT_PASSWORD}
    virksert:
      endpointURL: https://eformidling.dev/virksomhetssertifikat/
    sign:
      keystore:
        path: ${KEYSTORE_PATH}
        alias: ${KEYSTORE_ALIAS}
        password: ${KEYSTORE_PASSWORD}
        type: JKS
    auth:
      sas-token: ${SAS_TOKEN}

logging:
  level:
    org.springframework.ws.client.MessageTracing: TRACE
    org.springframework.ws.server.MessageTracing: TRACE
    no.difi.meldingsutveksling.serviceregistry.controller: TRACE
