spring:
    cloud:
        config:
            uri: http://eureka:8761/discovery/config
    profiles:
        active: staging
eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka:8761/discovery/eureka
app:
    logger:
        destination: qa-stream-meldingsutveksling.difi.no:443
difi:
    move:
        virksert:
            endpointURL: https://qa-meldingsutveksling.difi.no/virksomhetssertifikat/
        dpv:
            endpointURL: https://tt02.altinn.no/ServiceEngineExternal/CorrespondenceAgencyExternal.svc
        dpi:
            endpointURL: https://qaoffentlig.meldingsformidler.digipost.no/api/ebms
        krr:
            mp-endpoint-uri: https://test.kontaktregisteret.no/rest/v1/personer
            mp-dsf-endpoint-uri: https://test.kontaktregisteret.no/rest/v1/mf/personer
        auth:
            maskinporten-issuer: https://test.maskinporten.no/
        dpo:
            endpointURL: https://www.altinn.no
