server:
  port: 8080
management:
  server:
    port: 8090
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
        exclude: shutdown
    enabled-by-default: true
  metrics:
    tags:
      application: ${spring.application.name}
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/move_sr_nextmove
    username: move_sr
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

difi:
  move:
    virksert:
      endpointURL: https://eformidling.dev/virksomhetssertifikat/
    dpv:
      endpointURL: https://tt02.altinn.no/ServiceEngineExternal/CorrespondenceAgencyExternal.svc
    dpi:
      endpointURL: https://qaoffentlig.meldingsformidler.digipost.no/api/ebms
    krr:
      mp-endpoint-uri: https://test.kontaktregisteret.no/rest/v1/personer
      mp-dsf-endpoint-uri: https://test.kontaktregisteret.no/rest/v1/mf/personer
    sign:
      keystore:
        path: ${DIFI_MOVE_SIGN_KEYSTORE_PATH}
        alias: ${DIFI_MOVE_SIGN_KEYSTORE_ALIAS}
        password: ${DIFI_MOVE_SIGN_KEYSTORE_PASSWORD}
        type: JKS

app:
  logger:
    destination: test-stream-meldingsutveksling.dificloud.net:443

logging:
  level:
    org.springframework.ws.client.MessageTracing: TRACE
    org.springframework.ws.server.MessageTracing: TRACE
