spring:
  cloud:
    config:
      uri: http://eureka:8761/discovery/config
  profiles:
    active: production
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/discovery/eureka
app:
  logger:
    destination: stream-meldingsutveksling.difi.no:443
difi:
  move:
    virksert:
      endpointURL: https://meldingsutveksling.difi.no/virksomhetssertifikat/
    dpv:
      endpointURL: https://www.altinn.no/ServiceEngineExternal/CorrespondenceAgencyExternal.svc
    dpi:
      endpointURL: https://meldingsformidler.digipost.no/api/ebms
    krr:
      mp-endpoint-uri: https://kontaktregisteret.no/rest/v1/personer
      mp-dsf-endpoint-uri: https://kontaktregisteret.no/rest/v1/mf/personer
      print-url: https://kontaktregisteret.no/rest/v2/printSertifikat
    auth:
      maskinporten-issuer: https://maskinporten.no/
    fiks:
      svarut:
        certificate: classpath:svarut_public.pem
        forsendelsesserviceUrl: https://svarut.ks.no/tjenester/forsendelseservice/ForsendelsesServiceV9
        serviceRecordUrl: https://svarut.ks.no/tjenester/forsendelseservice/ForsendelsesServiceV6
      io:
        endpoint-url: https://api.fiks.ks.no
    elma:
      locatorUrl: http://smp.difi.no.publisher.edelivery.tech.ec.europa.eu/
    dpo:
      endpointURL: https://www.altinn.no
      serviceEditionCode: 170101
