name: Test

on:
  push:
    branches-ignore: [main]

jobs:
  call-workflow-maven-build:
    if: !contains(github.event.head_commit.message, '[run-ci]')
    uses: felleslosninger/github-workflows/.github/workflows/ci-maven-build.yml@main
    with:
      java-version: 21
      application-path: serviceregistry-server/
    secrets: inherit

  call-container-scan:
    if: !contains(github.event.head_commit.message, '[run-ci]')
    uses: felleslosninger/github-workflows/.github/workflows/ci-spring-boot-container-scan.yml@main
    with:
      java-version: 21
      application-path: serviceregistry-server/
    secrets: inherit
