name: Test

on:
  pull_request:
    branches: [ main ]

permissions:
  pull-requests: write
  contents: write
  issues: write
  repository-projects: read

jobs:
  run-pr-checks:
    uses: felleslosninger/github-workflows/.github/workflows/ci-pr-checks.yml@main
    with:
      application-type: spring-boot
      enable-auto-merge-dependabot: true
      enable-pr-title-verify: false
      enable-trivy-image-scan: true
      java-version: 25
      image-name: efm-service-registry
      auto-merge-types: "version-update:semver-patch"
      pull-request-title: ${{ github.event.pull_request.title }}
      pull-request-allowed-prefixes: "MOVE-,Bump"
      pull-request-case-sensitive-prefix: true
      maven-lifecycle: "verify"
    secrets: inherit
