name: Test

on:
  push:
    branches-ignore: [main]

jobs:
  call-workflow-maven-build:
    uses: felleslosninger/github-workflows/.github/workflows/ci-maven-build.yml@PF-1663-1
    with:
      java-version: 21
    secrets: inherit

  call-container-scan:
    uses: felleslosninger/github-workflows/.github/workflows/ci-spring-boot-container-scan.yml@PF-1663-1
    with:
      java-version: 21
      application-path: serviceregistry-server/
    secrets: inherit
